bird=["parrot","john","john"]
bird.extend(["crow","cow","hipopotemas"])
print(bird)
print('The extend function adds another list with the list')
bird.insert(3,"inserted")
print('The insert function adds an element at a specific position of the list')
print(bird)
x=bird.pop()
print('The pop function returns the last element and removes it from the list')
print(x)
print(x)
print(bird)
bird.sort()
print(bird)